### ISSUE TITLE
Multi-valued property returns "unhashable type: 'list' error 

### ISSUE THREAD

**Issue by PeterWalchhofer** [wetneb/openrefine-wikibase#115]
When I am querying the service with a multivalued E-Mail property (P968) I get an error. Other multi-valued properties, however, do work. Maybe the reason is that an E-Mail adress is being seen as an identifier and it runs into some error with the new commits?

Before commit `0c1909f16228be3c0d22ead1d9fb62337fc0fb2c` this worked.

**Comment by thadguidry** [comment]
The [P968](https://www.wikidata.org/wiki/Property:P968) email property **values** should look like this:
`mailto:thadguidry@gmail.com`
So maybe a parsing issue with the `:` colon or `@`? or the service doesn't correctly see it as a URI value as it should ([RFC 6068](https://en.wikipedia.org/wiki/Mailto))?
