### ISSUE TITLE
app uses debug mode in production

### ISSUE THREAD

**Issue by lucaswerkmeister** [wetneb/openrefine-wikibase#126]
[According to the Quart docs](https://pgjones.gitlab.io/quart/reference/source/quart.html?highlight=debug#id5), debug mode “should/must be `False` in production”, yet `app.py` unconditionally sets it to `True` in its call to `app.run()` at the end of the file. This seems like a bad idea.

**Comment by lucaswerkmeister** [comment]
The recommended run command when installing manually, and the one used in the docker container, should probably instead be:

```sh
hypercorn -b localhost:8000 app:app
```

If the venv is used correctly, `hypercorn` should be in the PATH already. (This also binds only to localhost instead of all interfaces, which I think is preferable. Exposing to the internet should IMHO be left to a proxy server that also handles HTTPS.)

**Comment by wetneb** [comment]
Thanks! It is funny you open this, I just wanted to document deployment better a few days ago (https://github.com/wetneb/openrefine-wikibase/issues/125). I have not tried deploying it with `hypercorn` yet, for now I am using `gunicorn`.

**Comment by lucaswerkmeister** [comment]
I mainly went for hypercorn because it’s already in the `.venv/bin` (though I don’t remember how I found it there… I think it might have been somewhere in the default `app.py` output?). I wouldn’t mind gunicorn either :shrug:
