### ISSUE TITLE
Exception caught: java.lang.NullPointerException

### ISSUE THREAD

**Issue by mshd** [wetneb/openrefine-wikibase#128]
17:41:05.347 [                   refine] POST /command/wikidata/preview-wikibase-schema (7ms)
17:41:05.362 [                  command] Exception caught (15ms)
java.lang.NullPointerException

Sometimes when I try to upload multiple fields I get this error from the terminal, meanwhile the issue page is just blank.
A more detailed error message would be great. I can't reproduce it now, but can send the archive if you life.

**Comment by mshd** [comment]
https://user-images.githubusercontent.com/17379661/144755510-1b956a5a-dacf-43ad-9d41-1ad0273acc2b.mp4

as soon as I add a property it guess blank

**Comment by wetneb** [comment]
Hi @mshd, thanks for this report!
That sounds like an issue for https://github.com/OpenRefine/OpenRefine, not this repository. Would you mind filing it there?
I would be interested in your project archive, and also in seeing the lines after `NullPointerException` which show how the error was reached.
Thanks again!

**Comment by mshd** [comment]
8:41:25.476 [                  command] Exception caught (12ms)
java.lang.NullPointerException
18:42:07.199 [                   refine] GET /command/core/get-history (41723ms)
18:42:07.578 [                   refine] POST /command/core/get-rows (379ms)
18:42:08.496 [                   refine] POST /command/core/compute-facets (918ms)
18:42:08.585 [                   refine] GET /command/core/get-preference (89ms)
18:42:10.320 [                   refine] GET /command/wikidata/login (1735ms)
18:42:10.338 [                   refine] GET /command/core/get-csrf-token (18ms)
18:42:10.355 [                   refine] POST /command/wikidata/preview-wikibase-schema (17ms)
18:42:10.398 [                  command] Exception caught (43ms)
java.lang.NullPointerException
18:42:48.936 [                   refine] GET /command/core/get-csrf-token (38538ms)
18:42:48.961 [                   refine] POST /command/wikidata/preview-wikibase-schema (25ms)
18:42:48.982 [                  command] Exception caught (21ms)
java.lang.NullPointerException
18:42:50.606 [                   refine] GET /command/core/get-csrf-token (1624ms)
18:42:50.629 [                   refine] POST /command/wikidata/preview-wikibase-schema (23ms)
18:42:52.435 [                   refine] GET /command/core/get-csrf-token (1806ms)
18:42:52.448 [                   refine] POST /command/wikidata/save-wikibase-schema (13ms)
18:42:52.469 [                   refine] GET /command/core/get-history (21ms)
18:42:52.825 [                   refine] GET /command/core/get-preference (356ms)
18:42:58.176 [                   refine] GET /command/wikidata/login (5351ms)
18:42:58.196 [                   refine] GET /command/core/get-csrf-token (20ms)
18:42:58.216 [                   refine] POST /command/wikidata/preview-wikibase-schema (20ms)
18:43:04.697 [                   refine] GET /command/core/get-csrf-token (6481ms)
18:43:04.706 [                   refine] POST /command/wikidata/preview-wikibase-schema (9ms)
18:43:07.250 [                   refine] GET /command/core/get-csrf-token (2544ms)
18:43:07.263 [                   refine] POST /command/wikidata/save-wikibase-schema (13ms)
18:43:07.286 [                   refine] GET /command/core/get-history (23ms)
18:43:07.610 [                   refine] GET /command/core/get-preference (324ms)
18:43:20.419 [                   refine] GET /command/core/get-csrf-token (12809ms)
18:43:20.450 [                   refine] POST /command/wikidata/preview-wikibase-schema (31ms)
18:43:20.470 [                  command] Exception caught (20ms)
java.lang.NullPointerException
18:43:22.013 [                   refine] GET /command/core/get-csrf-token (1543ms)
18:43:22.027 [                   refine] POST /command/wikidata/save-wikibase-schema (14ms)
18:43:22.046 [                   refine] GET /command/core/get-history (19ms)
18:43:22.480 [                   refine] GET /command/core/get-preference (434ms)

**Comment by mshd** [comment]
Here's the link to the archive https://drive.google.com/file/d/1yk1-8GSNctm__NfAGPJFano9fgi3mr96/view?usp=sharing
the bug happens when adding "PDDikti higher education institution ID" from Wikidata

**Comment by mshd** [comment]
ah I got it working, if I fill down it works. But null should just ignore it right?

**Comment by wetneb** [comment]
it should indeed!

**Comment by mshd** [comment]
Hmm now I'm quite lots a fails
![Screenshot from 2021-12-05 18-58-40](https://user-images.githubusercontent.com/17379661/144757845-97204ea6-a049-4ece-8009-69f32d022f08.png)

**Comment by wetneb** [comment]
I can see you are running 3.5-beta1, perhaps it would be worth updating to 3.5.0 (just a generic suggestion, on top of my mind I cannot think of a change between those two versions which should fix it, but also it does not hurt).

**Comment by mshd** [comment]
Ok thanks for the tip! Didn't think about it.

**Comment by wetneb** [comment]
This is a problem with editing, so it is outside the scope of this repository as indicated above.
