### ISSUE TITLE
Some items are not found by reconciliation ... maybe due to a large number of similar items?

### ISSUE THREAD

**Issue by VojtechDostal** [wetneb/openrefine-wikibase#130]
I am using https://wikidata.reconci.link/cs/api

Lets say we have this table with two data rows:

street | admist.entity | country
-- | -- | --
Smetanova | Q541071 | Q213
Boženy Němcové | Q541071 | Q213

I want to reconcile the street names in the first column. 
Settings: 

![image](https://user-images.githubusercontent.com/21329813/146800144-b230c0e8-cee8-4c5a-bbbd-7973c9da3838.png)

Only the second street is successfully reconciled although Smetanova (https://www.wikidata.org/wiki/Q45168712) exists too.
This is not limited to https://www.wikidata.org/wiki/Q45168712, I have other similar examples like this. 
I suspect it could be due to an extremely large number of items named "Smetanova" in Wikidata. Only the first few (hundred) are loaded and taken into consideration and https://www.wikidata.org/wiki/Q45168712 likely isn't among them...

**Comment by wetneb** [comment]
yes! it seems hard to solve this problem with the current architecture

**Comment by wetneb** [comment]
Therefore closing.
