### ISSUE TITLE
Latest Jinja causing Docker build to fail. 

### ISSUE THREAD

**Issue by paulduchesne** [wetneb/openrefine-wikibase#137]
**Observed behaviour**

Docker will not build reconcile_1 container due to new versions of Jinja (> 3.1) including [breaking changes](https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-0).

> reconcile_1  | Traceback (most recent call last):
> reconcile_1  |   File "app.py", line 8, in <module>
> reconcile_1  |     from quart import Quart, render_template, request, g
> reconcile_1  |   File "/usr/local/lib/python3.7/site-packages/quart/__init__.py", line 3, in <module>
> reconcile_1  |     from jinja2 import escape, Markup
> reconcile_1  | ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.7/site-packages/jinja2/__init__.py)
> openrefine-wikibase_reconcile_1 exited with code 1

**Proposed solution**

-> add ```jinja2==3.0.3``` to ```requirements.txt```

Happy to open a PR for this fix.

**Comment by wetneb** [comment]
Thanks for reporting! A PR would be amazing.

**Comment by wetneb** [comment]
Closed by #138.
