### ISSUE TITLE
Custom manifest and IRI url

### ISSUE THREAD

**Issue by YOUR1** [wetneb/openrefine-wikibase#139]
Hi,

I noticed a bug in the latest version of OpenRefine. When using `https://` for the reconciliation endpoint in a custom manifest file, for example:
```
  "reconciliation": {
    "endpoint": "https://reconciliation.some-endpoint.com/${lang}/api"
  }
```

The reconcilitation works fine when editing a data file, for example reconciling columns. But after that, when you want to create a scheme the columns won't be recognized as reconcilitated ones. They stay gray, thus the effect is that you can't create a scheme.

**Comment by wetneb** [comment]
Whether the reconciliation endpoint uses HTTP or HTTPS should not matter, but it is important that the siteIri remains consistent throughout the configuration of the reconciliation service and that of the Wikibase manifest.
