### ISSUE TITLE
Should empty properties scores to 0?

### ISSUE THREAD

**Issue by paulgirard** [wetneb/openrefine-wikibase#142]
If I reconcile using a extra property like "family name", entities which match on the label but does not have any available value for the P734 property will score this feature to 0.

In my reconciliation use cases I would prefer that empty values were considered differently than not-matching-at-all ones.
Indeed lacking of data fields actually lower scores were we can't actually assess if the value requested is accurate since we just don't know.
This behavior restrain me to use complex data for scoring because of entity description heterogeneity.

Maybe one way to deal with this would be to score not available properties to None/null which would not be considered in the global score. 
This would make the property lack of data visible to any feature score enabled client while not lowering global score where we don't know.

An example:

```json
{
    "q0": {
        "query": "Roger Picard",
        "type": "Q5",
        "properties": [
            {
                "pid": "P734",
                "v": "Picard"
            }
        ]
    }
}
```
Outputs:
```json
{
    "q0": {
        "result": [
            {
                "description": "Canadian ice hockey player",
                "features": [
                    {
                        "id": "P734",
                        "value": 100
                    },
                    {
                        "id": "all_labels",
                        "value": 100
                    }
                ],
                "id": "Q7257159",
                "match": true,
                "name": "Roger Picard",
                "score": 100.0,
                "type": [
                    {
                        "id": "Q5",
                        "name": "human"
                    }
                ]
            },
            {
                "description": "American politician",
                "features": [
                    {
                        "id": "P734",
                        "value": 0
                    },
                    {
                        "id": "all_labels",
                        "value": 100
                    }
                ],
                "id": "Q16189449",
                "match": false,
                "name": "Roger Picard",
                "score": 71.42857142857143,
                "type": [
                    {
                        "id": "Q5",
                        "name": "human"
                    }
                ]
            },
            {
                "description": "French jurist",
                "features": [
                    {
                        "id": "P734",
                        "value": 0
                    },
                    {
                        "id": "all_labels",
                        "value": 100
                    }
                ],
                "id": "Q24007809",
                "match": false,
                "name": "Roger Picard",
                "score": 71.42857142857143,
                "type": [
                    {
                        "id": "Q5",
                        "name": "human"
                    }
                ]
            },
            {
                "description": null,
                "features": [
                    {
                        "id": "P734",
                        "value": 0
                    },
                    {
                        "id": "all_labels",
                        "value": 100
                    }
                ],
                "id": "Q99484435",
                "match": false,
                "name": "Roger Picard",
                "score": 71.42857142857143,
                "type": [
                    {
                        "id": "Q5",
                        "name": "human"
                    }
                ]
            },
            {
                "description": "French painter",
                "features": [
                    {
                        "id": "P734",
                        "value": 0
                    },
                    {
                        "id": "all_labels",
                        "value": 100
                    }
                ],
                "id": "Q104484312",
                "match": false,
                "name": "Roger Picard",
                "score": 71.42857142857143,
                "type": [
                    {
                        "id": "Q5",
                        "name": "human"
                    }
                ]
            }
        ]
    }
}
```

**Comment by wetneb** [comment]
Hello,
Yes I can very much relate to your use case and I think your request is legitimate.
I am keen to think about which features could be added / changed to better expose which property was present or not on the Wikibase instance.
I would not change the global scoring mechanism as things stand, because tweaking it might break users' workflows in other cases. But if you want to use the service with a different scoring mechanism it should be relatively straightforward to run your own instance with the tweaked scoring.

**Comment by paulgirard** [comment]
Oh really?
That's tempting indeed.
I see everything runs in a docker and that this python code is basically a proxy to wikimedia API so yes looks easy to deploy and tune. Oh that's a very good news :+1: 

Now, how can I make my experiments useful to others including dev/spec team?
I propose to fork and work on a specific branch of my own and will try to keep update with the upstream as much as possible and let you pick ideas or commit if appropriate. I'll also try to document the methodological reasons to tune the scoring the way I do.
What do you think? 

I need this for linking a large dataset (12.5k people) which should happen this fall (depends on funding...).
So don't be surprise, it'll take time before coming back about this.

Last: I guess this issue can be closed?


ps: actually looks like this could make an interesting talk maybe at FOSDEM

**Comment by wetneb** [comment]
> I need this for linking a large dataset (12.5k people) which should happen this fall (depends on funding...).
> So don't be surprise, it'll take time before coming back about this.

Very keen to hear more about your project any time!

> ps: actually looks like this could make an interesting talk maybe at FOSDEM

That would be lovely! I am keen to attend FOSDEM next year.
