### ISSUE TITLE
Let users fetch descriptions or sitelinks

### ISSUE THREAD

**Issue by wetneb** [wetneb/openrefine-wikibase#17]
The data extension protocol should let users fetch descriptions, sitelinks, aliases, and other things like that. These could be added by default to the suggested properties.

**Comment by wetneb** [comment]
We could also let users fetch raw Qids (in order to avoid using the "cell.recon.match.id" GREL expression).

https://twitter.com/Ettore_Rizza/status/932994764617715713

**Comment by Aubreymcfato** [comment]
Also, we could let user "add from reconciled values" in the language they prefer... For example, if I reconcile an author, I can only add some values (sex, country, etc.) in English, but I want them in Italian.

**Comment by ettorerizza** [comment]
@Aubreymcfato Just to make sure there is no misunderstanding: for the moment, if you make the reconciliation with the service in Italian ( [https://tools.wmflabs.org/openrefine-wikidata/it/api](https://tools.wmflabs.org/openrefine-wikidata/it/api) ), all the rest will be provided in Italian. 

![screenshot-127 0 0 1-3333-2018 02 19-09-49-53](https://user-images.githubusercontent.com/6286410/36369297-15cd7e26-155b-11e8-899e-60f1b3ddcfae.png)

You would like to be able to change language along the way, is that it?

**Comment by wetneb** [comment]
Terms (labels, descriptions and aliases) have been implement but there is another request for sitelinks on the mailing list:
https://groups.google.com/forum/#!topic/openrefine/nplJxIFOPR8

**Comment by ettorerizza** [comment]
Looks like a popular demand in the librarian world : https://twitter.com/daieuxdailleurs/status/1085455759117303813
