### ISSUE TITLE
Add Wiki page on how to run locally

### ISSUE THREAD

**Issue by thadguidry** [wetneb/openrefine-wikibase#37]
and add the link to that new Wiki page on the README.md :)

**Comment by thadguidry** [comment]
Please hurry up with those docs. :)  I'm tired of seeing this:
```
Microsoft Windows [Version 10.0.17134.112]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\THAD>python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

C:\Users\THAD>cd openrefine-wikidata

C:\Users\THAD\openrefine-wikidata>python app.py
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    import bottle
ModuleNotFoundError: No module named 'bottle'

C:\Users\THAD\openrefine-wikidata>pip install bottle
Collecting bottle
  Downloading https://files.pythonhosted.org/packages/bd/99/04dc59ced52a8261ee0f965a8968717a255ea84a36013e527944dbf3468c/bottle-0.12.13.tar.gz (70kB)
    100% |████████████████████████████████| 71kB 140kB/s
Installing collected packages: bottle
  Running setup.py install for bottle ... done
Successfully installed bottle-0.12.13

C:\Users\THAD\openrefine-wikidata>python app.py
Traceback (most recent call last):
  File "app.py", line 7, in <module>
    from docopt import docopt
ModuleNotFoundError: No module named 'docopt'

C:\Users\THAD\openrefine-wikidata>pip install docopt
Collecting docopt
  Downloading https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Installing collected packages: docopt
  Running setup.py install for docopt ... done
Successfully installed docopt-0.6.2

C:\Users\THAD\openrefine-wikidata>python app.py
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    from wdreconcile.engine import ReconcileEngine
  File "C:\Users\THAD\openrefine-wikidata\wdreconcile\engine.py", line 1, in <module>
    from config import *
ModuleNotFoundError: No module named 'config'

C:\Users\THAD\openrefine-wikidata>
```

**Comment by wetneb** [comment]
hey @thadguidry if you ask me to "hurry up", this is not likely to happen any time soon…

**Comment by thadguidry** [comment]
@wetneb Oh Antonin, you know already my personality, completely laid back... if this happens in 1 year or more, its fine... I was just showcasing the steps that I performed without docs just to see.  When I said "hurry up" it was meant in jest, sorry if you didn't feel that. Text is the worst feeling conductor in the world. lololol

**Comment by wetneb** [comment]
@thadguidry yeah sorry to react harshly… I have a lot on my plate currently so I have a sort of adverse reaction when being put under more pressure.

**Comment by thadguidry** [comment]
For Windows 10 x64 users, they can:
1. Install Python 3.x latest
2. Download the compiled python-levenshtein wheel file (.whl) from https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-levenshtein
3. cd to the downloaded file location `cd E:\Downloads` or wherever you downloaded to.
4. Install with command `pip install python_Levenshtein-0.12.0-cp37-cp37m-win_amd64.whl`
5. Install the rest of requirements with command `pip install -r requirements.txt`
6. Clone or download the openrefine-wikidata repo and extract it to a folder.
7. cd to the repo folder location `cd openrefine-wikidata`
8. Start application with `python app.py`
```
C:\Users\THAD\openrefine-wikidata>python app.py
Bottle v0.12.13 server starting up (using WSGIRefServer())...
Listening on http://localhost:8000/
Hit Ctrl-C to quit.
```
9. Throw Antonin some coin for working hard on this.

**Comment by wetneb** [comment]
Awesome, thanks a lot!

**Comment by wetneb** [comment]
Done in the README.
