### ISSUE TITLE
Performance challenges

### ISSUE THREAD

**Issue by susannaanas** [wetneb/openrefine-wikibase#40]
The reconcilition service output is remarkably low. It causes part of the requests to time out and cause errors. The processing times are very long, and error rates high, resulting in a lot of manual work.

The previews don't generally work, and therefore the links to Wikidata cannot be used as substitute for automatic lookup. The link contains the Wikidata ID, which can bee visually seen in the browser and checked that way.

It would be handy not to have to reconcile already reconciled data, but the copy reconciliation data produces no results.

I have a database of 3000 items and several reconciled properties. I am not running the very latest version (I cannot find the version number) of 3.0 Beta.

I have tested with different internet connections, and that does not seem to be the reason.

**Comment by wetneb** [comment]
Yes, it seems that processing times have more or less tripled recently. I will investigate.

**Comment by wetneb** [comment]
Restarting the interface seems to have restored the situation to normal performance.

**Comment by thadguidry** [comment]
@wetneb I'm currently seeing degradation with the suggestion flyouts being filled in, just the box and 3 buttons but no pictures or entity description...seems to take about 20 secs to populate the flyout once I click on a hyperlink for a match candidate.

**Comment by wetneb** [comment]
After a few hours https://wikidata.reconci.link/ shows good stats compared to the previous endpoint. I will close this as it is rather old now. For more long term discussion about performance improvements, see https://phabricator.wikimedia.org/T244847
