### ISSUE TITLE
Wikidata properties reconciliation

### ISSUE THREAD

**Issue by ettorerizza** [wetneb/openrefine-wikibase#42]
Hello Antonin, 

Are there plans to also reconcile the properties of Wikidata and not just the items? This would be very useful to facilitate mapping with other ontologies such as schema.org.

**Comment by wetneb** [comment]
That has been requested before and would definitely be useful indeed!

**Comment by wetneb** [comment]
Out of scope for this repository: another reconciliation endpoint should be designed for that (although it could reuse some parts I guess).
