### ISSUE TITLE
Duplicate items created when creating multiple new linked items in one update

### ISSUE THREAD

**Issue by jbothma** [wetneb/openrefine-wikibase#44]
I think there's a problem creating multiple interlinked items in one update.

I'm trying to create a mayor and an executive and link the to each other and an existing municipality in one update. What ends up happening is the following:
- an item Q57414669 is created without a label, with just the `part of` statement to Q57414667
- an item Q57414667 is created without a label, with the `has part` statement to Q57414666
- an item Q57414666 is created with a label, with everything except the `part of` statement which Q57414669 got.
- the municipality Q1983450 gets an `executive body` statement to Q57414667
- an item Q57414665 is created with a label and everything except the `has part` statement which Q57414667 got

here's the "Export to quick statements" of the same update set, after running the updates
```
Q57414667	Laf	"Burgermeesterskommittee van Newcastle"
Q57414667	Len	"Mayoral Committee of Newcastle"
Q57414667	Daf	"uitvoerende gesag van die Newcastle Plaaslike Munisipaliteit"
Q57414667	Den	"executive authority of the Newcastle Local Municipality"
Q57414667	P17	Q258
Q57414667	P1001	Q1983450
Q57414667	P279	Q640506
Q57414667	P527	Q57414669
Q1983450	P208	Q57414667
Q1983450	P1313	Q57414669
Q57414669	Len	"Executive Mayor of Newcastle Local Municipality"
Q57414669	Laf	"Uitvoerende Burgermeester van Newcastle Plaaslike Munisipaliteit"
Q57414669	Den	"head of government of the Newcastle Local Municipality"
Q57414669	Daf	"regeringshoof van die Newcastle Plaaslike Munisipaliteit"
Q57414669	P17	Q258
Q57414669	P361	Q57414667
Q57414669	P1001	Q1983450
Q57414669	P31	Q294414
```

![openrefine-wikidata-dupes-1](https://user-images.githubusercontent.com/235801/47076286-ada57400-d1fe-11e8-96a4-c26069d8e2f8.png)
![openrefine-wikidata-dupes-2](https://user-images.githubusercontent.com/235801/47076294-b26a2800-d1fe-11e8-8292-91056367de55.png)
![openrefine-wikidata-dupes-contributions](https://user-images.githubusercontent.com/235801/47076359-d4fc4100-d1fe-11e8-8287-8e19bfb3fb47.png)

**Comment by wetneb** [comment]
@jbothma thanks for the report. Do you think you could share your project to help me debug this? I would be interested in looking at the project state before the items are created on Wikidata.

**Comment by jbothma** [comment]
Sure! What's the best way to do that? Should I upload the project tgz
somewhere? If so, any suggestions?

**Comment by wetneb** [comment]
Yes that would be great. You should be able to upload the tgz on GitHub directly (you can attach files to your comments).

**Comment by jbothma** [comment]
[South-Africa-Outline-Data-Geography-csv.openrefine(2).tar.gz](https://github.com/wetneb/openrefine-wikibase/files/2487203/South-Africa-Outline-Data-Geography-csv.openrefine.2.tar.gz)

**Comment by jbothma** [comment]
Heads-up I've been recycling the items that didn't have labels by adding labels for new items I need otherwise and ensuring all the old links are removed. So they might have surprising names now

**Comment by jbothma** [comment]
**Important to note**: if this happens, it's really important to re-reconcile the relevant columns, otherwise statements might be added to the wrong (recycled) items, presumably because OpenRefine has it reconciled to the wrong Q-number.

**Comment by wetneb** [comment]
This was a bug in OpenRefine which has been fixed in the meantime, in any case nothing related to this repository.
