### ISSUE TITLE
How to reconcile based on a known Wikipedia article as additional property?

### ISSUE THREAD

**Issue by susannaanas** [wetneb/openrefine-wikibase#45]
I am sorry if this is basic knowledge or if I have asked it before, but I could not find the answer. Thanks a lot!

**Comment by wetneb** [comment]
You can directly reconcile a column of Wikipedia links. For instance if a cells contains "https://en.wikipedia.org/wiki/Douglas Adams" it will be reconciled to Q42.

So if you only have wikipedia links for some rows, you could just reconcile the column with the wikipedia links, and then copy over the reconciliation results to the main column with the names. I think the "copy reconciliation results" could potentially be used for that, but I am not sure.

At the moment I do not think this feature can be used via properties though. But it would make a lot of sense to add it, so I am keeping this issue open.

**Comment by susannaanas** [comment]
Thanks a lot again!
