### ISSUE TITLE
Ability to disable/disable part of schema for specific updates

### ISSUE THREAD

**Issue by jbothma** [wetneb/openrefine-wikibase#46]
It'd be nice to be able to apply only parts of the schema for certain facets of the data.

When items already exist and have some statements or terms defined differently from my dataset, I don't want to replace those terms, and I don't want to duplicate the statement with my slightly different statements.

Perhaps if I can reconcile them with something like https://github.com/wetneb/openrefine-wikibase/issues/42 this wouldn't be needed.

Currently I delete the part of the schema that would modify someone else's good description which just happens to be different from mine. Same with statements - if the same statement already exists but with one more or one less qualifier, if I'm not careful to delete the schema that would create the statement, I end up duplicating it

**Comment by wetneb** [comment]
Currently what I do is blanking the cells for which I don't want to upload data.

In the future I would like to add multiple modes on a statement, to configure how it is matched with existing data. (For instance, only add a description if there is non yet, only add a statement if there is none for this property…)

**Comment by wetneb** [comment]
This issue should be in the OpenRefine repository - I think it matches this issue: https://github.com/OpenRefine/OpenRefine/issues/2438
