### ISSUE TITLE
null value for properties in request causes 500 internal server error

### ISSUE THREAD

**Issue by mvolz** [wetneb/openrefine-wikibase#48]
This request causes an internal server error: https://tools.wmflabs.org/openrefine-wikidata/en/api?query=%7B%22query%22%3A%22en%22%2C%22limit%22%3A1%2C%22type%22%3A%5B%22Q1288568%22%2C%22Q33742%22%2C%22Q951873%22%2C%22Q33384%22%2C%22Q34770%22%5D%2C%22type_strict%22%3A%22any%22%2C%22properties%22%3Anull%7D

Removing the "properties": null part and it works: https://tools.wmflabs.org/openrefine-wikidata/en/api?query=%7B%22query%22%3A%22en%22%2C%22limit%22%3A1%2C%22type%22%3A%5B%22Q1288568%22%2C%22Q33742%22%2C%22Q951873%22%2C%22Q33384%22%2C%22Q34770%22%5D%2C%22type_strict%22%3A%22any%22%7D

Null seems to work okay in other optional fields i.e.

https://tools.wmflabs.org/openrefine-wikidata/en/api?query=%7B%22query%22:%22boston%22,%22properties%22:null,%22type%22:%22Q515%22%7D

causes an error but 

https://tools.wmflabs.org/openrefine-wikidata/en/api?query=%7B%22query%22:%22boston%22,%22limit%22:null,%22type%22:%22Q515%22%7D 

is fine.

**Comment by wetneb** [comment]
`properties: null` and `limit: null` are incorrect according to the specs so let's close this by saying that it's fine to return an error in that case (although it would be more elegant if it were not an internal error ^^)
