### ISSUE TITLE
Copy references across statements in Wikidata schema

### ISSUE THREAD

**Issue by abartov** [wetneb/openrefine-wikibase#49]
Began using OpenRefine seriously, and the Wikidata support is just fantastic. One thing that would save some time is if after adding a reference in the Wikidata schema, the reference could be "filled down" or copied and pasted, or otherwise duplicated, for cases where all the statements are supported by the same source (e.g. census data).

**Comment by wetneb** [comment]
Awesome, thanks for the feedback. The request is also tracked here:
https://github.com/OpenRefine/OpenRefine/issues/1912

**Comment by wetneb** [comment]
Closing this as this is tracked in OpenRefine's issue tracker above.
