### ISSUE TITLE
Show progress in console while reconciling

### ISSUE THREAD

**Issue by abartov** [wetneb/openrefine-wikibase#50]
Reconciling seems to hang sometimes.  It would be good to emit some progress indicators in the console (if not in the UI), to enable us to notice a hang and restart OpenRefine.  Especially on slower connections, it's crucial to be able to tell apart slowness from a hang.

**Comment by wetneb** [comment]
There is already a progress indicator in OpenRefine's UI (the percentage of task completed), how else do you suggest we report progress?

**Comment by abartov** [comment]
The progress indicator in the UI doesn't show where time is being spent.  To tell apart a hang from mere slowness, it would be useful to be able to see e.g. each API request start time (not all the lookups during interactive use -- just during reconciling).  Then one can compare the elapsed time since the last printed API call time to the time between that and the previous calls, and if it's, say 20x longer, conclude there may not be a point in waiting any longer.

**Comment by wetneb** [comment]
Makes sense. We already report any errors encountered during reconciliation in the console, but we could probably add more logging there for that.

**Comment by thadguidry** [comment]
@wetneb Is the request timeout configurable by users, or should be made so (preferences.vt maybe)? Or is there already an enhancement issue for that need ?

**Comment by wetneb** [comment]
We have https://github.com/OpenRefine/OpenRefine/issues/1235 which is quite close. Similarly we have https://github.com/OpenRefine/OpenRefine/issues/1809 for the data extension protocol.

**Comment by wetneb** [comment]
That's a problem for OpenRefine, not for this service.
