### ISSUE TITLE
Remember history of edit summaries

### ISSUE THREAD

**Issue by abartov** [wetneb/openrefine-wikibase#51]
When processing a large data set gradually, the edit summary may often be precisely the same, e.g. "Adding population numbers based on 2011 census".  It would be useful not to have to re-type it every time.

**Comment by wetneb** [comment]
@abartov which version of OpenRefine are you using, and which browser? Normally this was solved in 3.1.

**Comment by abartov** [comment]
Using 3.1 in Chrome.

**Comment by wetneb** [comment]
Closing as I have transferred this to the correct repository in https://github.com/OpenRefine/OpenRefine/issues/1778.
