### ISSUE TITLE
How to use with any Wikibase (not just Wikidata)?

### ISSUE THREAD

**Issue by tuukka** [wetneb/openrefine-wikibase#55]
We start to have more Wikibase instances in addition to Wikidata. Could the same service work for all of them - perhaps provide an endpoint url as a query parameter?

**Comment by wetneb** [comment]
Hi @tuukka,

The service is not designed to run against multiple Wikibase instances at once, however it should be easy to run your own instance of the service and configure it to work with the Wikibase instance of your choice. Just copy [`config_wikidata.py`](https://github.com/wetneb/openrefine-wikibase/blob/master/config_wikidata.py) to `config.py` and change the values in there to point to your own Wikibase instance. Let me know if anything goes wrong!

**Comment by wetneb** [comment]
@tuukka have you had any luck configuring this service for another Wikibase?

**Comment by tuukka** [comment]
@wetneb I'm sorry for not replying sooner! I'm working on @susannaanas's project so need to prioritise with her. I had a quick look now and found these potential issues:
* `propertypath.py` and `typematcher.py` hardcode the Wikidata prefixes
* `sparqlwikidata.py` hardcodes the Wikidata SPARQL endpoint
* `app.py` hardcodes Q35120 "entity | something that exists in the identified universe"
* `propertypath.py` hardcodes Q19847637 "Wikidata property for an identifier | Wikidata property to identify something in an external source"
* `engine.py` and `propertypath.py` hardcode P31 "instance of"
* `propertypath.py`, `suggest.py` and `typematcher.py` hardcode P279 "subclass of"

Perhaps (our) next step would be to test if changing these values is enough to get this working against a new wikibase?

**Comment by wetneb** [comment]
Ok, I didn't realize these values were still hardcoded there, sorry! I thought I had migrated everything to the config file. Yes that sounds like a good plan.

We still haven't made much progress on https://phabricator.wikimedia.org/T197588, sadly.

**Comment by wetneb** [comment]
Closed by #56.
