### ISSUE TITLE
Fetching monolingual text value fails

### ISSUE THREAD

**Issue by wetneb** [wetneb/openrefine-wikibase#59]
See https://github.com/OpenRefine/OpenRefine/issues/2034 and https://github.com/OpenRefine/OpenRefine/issues/1809

**Comment by mnaydan** [comment]
@wetneb I am getting this exact same Wikidata preview error when trying to add columns from reconciled values in OpenRefine version 3.3. I tried upgrading to v. 3.4 beta 2 hoping it would fix it, but the error persists.

**Comment by wetneb** [comment]
@mnaydan this must be due to the change of URL of the reconciliation service. The new URL is `https://wdreconcile.toolforge.org/en/api`. You will sadly need to reconcile your column again with this service (you could extract the matched Qids in a new column first using the `cell.recon.match.id` expression, so that the new reconciliation is quick)

**Comment by mnaydan** [comment]
Thanks, @wetneb. I can confirm that this was the problem and your suggested solution fixed it (the extract Qids tip was very helpful!)
