### ISSUE TITLE
"Upload edits to Wikidata" no longer does changes

### ISSUE THREAD

**Issue by tholbach** [wetneb/openrefine-wikibase#63]
I have started to use OpenRefine two weeks ago to update objects on Wikidata - and it's awesome. Unfortunately, during the last days I have no longer been able to upload my edits to Wikidata. 
The process is as usual, I need to login and give a quick statement what I'm doing. After that nothing happens. The logs in the console don't give me a hint what could possibly be wrong. 
If you need any additional info, please let me know.

**Comment by wetneb** [comment]
Have you tried logging out and in again?

**Comment by tholbach** [comment]
Yes, logged in again, restarted OpenRefine, restarted my computer, reconciled the related data. Quite everything that came to my mind 😄

**Comment by wetneb** [comment]
Interesting! Which version of OpenRefine are you using? Can you share the logs in the console?

**Comment by tholbach** [comment]
So, this is pretty much everything starting from the moment where I "Upload edits to Wikidata" including a new login. 
![image](https://user-images.githubusercontent.com/16371850/63855048-ca721280-c99e-11e9-9584-2404688ab90b.png)
If you need any of those in more detail, let me know.

**Comment by wetneb** [comment]
It would be useful if you could access the OpenRefine server logs (in the terminal console). If you run OpenRefine on Windows or Linux there should be a black terminal where these logs should be shown. If you are using MacOS here are the steps to obtain these logs:
https://github.com/OpenRefine/OpenRefine/wiki/Installation-Instructions#obtaining-server-logs-on-mac

**Comment by tholbach** [comment]
Ah, perfect. I was looking everywhere if there is any way to get actual logs out of OpenRefine. 
It turns out, I had not fully re-reconciled one of the values that was present - but just re-chosen one of the suggested values of the reconcilation process.

`14:57:19.076 [                   refine] POST /command/core/get-all-preferences (51ms)
14:57:27.881 [                   refine] POST /command/wikidata/login (8805ms)
14:57:29.468 [..kibaseapi.ApiConnection] API warning [main]: Subscribe to the mediawiki-api-announce mailing list at <https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce> for notice of API deprecations and breaking changes. Use [[Special:ApiFeatureUsage]] to see usage of deprecated features by your application. (1587ms)
14:57:29.469 [..kibaseapi.ApiConnection] API warning [login]: Main-account login via "action=login" is deprecated and may stop working without warning. To continue login with "action=login", see [[Special:BotPasswords]]. To safely continue using main-account login, see "action=clientlogin". (1ms)
14:57:29.504 [                   refine] POST /command/wikidata/preview-wikibase-schema (35ms)
14:57:51.214 [                   refine] POST /command/wikidata/perform-wikibase-edits (21710ms)
14:57:51.276 [..mWikibaseEditsOperation] Performing edits (62ms)
14:57:51.278 [..ting.EditBatchProcessor] Requesting documents (2ms)
org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorException: [modification-failed] [[Q66618483|Q66618483]] not found
	at org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorHandler.throwMediaWikiApiErrorException(MediaWikiApiErrorHandler.java:65)
	at org.wikidata.wdtk.wikibaseapi.ApiConnection.checkErrors(ApiConnection.java:466)
	at org.wikidata.wdtk.wikibaseapi.ApiConnection.sendJsonRequest(ApiConnection.java:406)
	at org.wikidata.wdtk.wikibaseapi.WbEditingAction.performAPIAction(WbEditingAction.java:716)
	at org.wikidata.wdtk.wikibaseapi.WbEditingAction.wbSetClaim(WbEditingAction.java:550)
	at org.wikidata.wdtk.wikibaseapi.StatementUpdate.performEdit(StatementUpdate.java:222)
	at org.wikidata.wdtk.wikibaseapi.TermStatementUpdate.performEdit(TermStatementUpdate.java:370)
	at org.wikidata.wdtk.wikibaseapi.WikibaseDataEditor.updateTermsStatements(WikibaseDataEditor.java:588)
	at org.openrefine.wikidata.editing.EditBatchProcessor.performEdit(EditBatchProcessor.java:156)
	at org.openrefine.wikidata.operations.PerformWikibaseEditsOperation$PerformEditsProcess.run(PerformWikibaseEditsOperation.java:192)
	at java.lang.Thread.run(Thread.java:748)
14:57:53.432 [                   refine] GET /command/core/get-history (2154ms)
14:57:53.605 [                   refine] GET /command/core/get-project-metadata (173ms)
14:57:53.616 [                   refine] GET /command/core/get-models (11ms)
14:57:53.636 [                   refine] POST /command/core/get-rows (20ms)
14:57:53.718 [                   refine] POST /command/core/compute-facets (82ms)
14:57:53.909 [                   refine] POST /command/wikidata/preview-wikibase-schema (191ms)`

Thank you so much!
