### ISSUE TITLE
Reconcile against something else than label/name ?

### ISSUE THREAD

**Issue by tfrancart** [wetneb/openrefine-wikibase#65]
Hello

It seems this reconciliation service, and the reconciliation API specification always reconcile based on the label/name of the entities.

I have a dataset containing identifiers (in my case, ISBN or ISSN numbers for books or magazine), but sometimes I don't have their titles/names, or sometimes the title is unreliable, but the identifier is. I would like to _reconcile against the identifier property in Wikidata_ (in my case, wdt:P236, ISSN), not against the label.

Can this be done in this reconciliation service implementation ? can the code be adapted to do that, or would there be a limitation in the wikibase API itself ?

If I still try to reconcile against a title, with an extra criteria on the ISSN number, would I get results even if the title is empty but the ISSN number matches ?

Thanks and Cheers

**Comment by wetneb** [comment]
Yes this can be done. See this tutorial:
https://www.wikidata.org/wiki/Wikidata:Tools/OpenRefine/Editing/Tutorials/Basic_editing
