### ISSUE TITLE
Why does a reconcile on country code "DEU" works while value "NLD" does not return any result ?

### ISSUE THREAD

**Issue by tfrancart** [wetneb/openrefine-wikibase#69]
```
https://tools.wmflabs.org/openrefine-wikidata/en/api?queries={ "q0" : { "query" : "DEU", "limit": 1, "type": "Q6256", "type_strict" : "all" }}
```

returns one result.

```
https://tools.wmflabs.org/openrefine-wikidata/en/api?queries={ "q0" : { "query" : "NLD", "limit": 1, "type": "Q6256", "type_strict" : "all" }}
```

Does not return anything.

However, double-checking https://www.wikidata.org/wiki/Q183 (Germany) and https://www.wikidata.org/wiki/Q55 (Netherlands) I see that :
  - both of them have P298 (code ISO 3166-1 alpha-3) set to the 3 letters code
  - this code is repeated in an alias in some language for both of them ("DEU" is an alias for Germany in Dutch, "NLD" is an alias for Netherlands in Spanish)

how does one explain this behavior ?

I have quite a few 3-letters country codes that cannot be reconciled, like NLD : URY, CHE, ZAF, and 38 other values.

**Comment by tfrancart** [comment]
Hmmm, didn't take me too long to figure out that the `limit` parameter causes the problem : 

```
https://tools.wmflabs.org/openrefine-wikidata/en/api?queries={ "q0" : { "query" : "NLD", "type": "Q6256", "type_strict" : "all" }}
```

works, while 

```
https://tools.wmflabs.org/openrefine-wikidata/en/api?queries={ "q0" : { "query" : "NLD", "limit": 1, "type": "Q6256", "type_strict" : "all" }}
```

does not.

is it expected ?

**Comment by tfrancart** [comment]
Also, I note some very strange behavior with the `limit` parameter :

With value 1 : `https://tools.wmflabs.org/openrefine-wikidata/en/api?queries={ "q0" : { "query" : "NLD", "limit": 1, "type": "Q6256", "type_strict" : "all" }}` - does not return any result
With value 2 : `https://tools.wmflabs.org/openrefine-wikidata/en/api?queries={ "q0" : { "query" : "NLD", "limit": 2, "type": "Q6256", "type_strict" : "all" }}` - does not return any result
With value 3 : `https://tools.wmflabs.org/openrefine-wikidata/en/api?queries={ "q0" : { "query" : "NLD", "limit": 3, "type": "Q6256", "type_strict" : "all" }}` - returns some results that are obviously wrong, seems that the type filtering is not taken into account

**Comment by tfrancart** [comment]
Side question : this is a case where I know I need to reconcile against a known specific property in Wikidata : P298 (code ISO 3166-1 alpha-3). Can I tell this to the reconcile API ? I don't think so.

**Comment by wetneb** [comment]
This is because the `limit` parameter is also passed to the search calls in the MediaWiki API.

The country does not show up high up in the search results, so it will not show up in the reconciliation results:
https://www.wikidata.org/w/index.php?search=&search=NLD&title=Special%3ASearch&go=Go&ns0=1&ns120=1

If you try to reconcile something based on a unique identifier you should not use the identifier as main query but rather as property:
https://tools.wmflabs.org/openrefine-wikidata/en/api?queries=%7B%22q0%22%3A%7B%22query%22%3A%22some+random+text%22%2C%22properties%22%3A%5B%7B%22pid%22%3A%22P298%22%2C%22v%22%3A%22NLD%22%7D%5D%7D%7D

Without URL encoding: `{"q0":{"query":"some+random+text","properties":[{"pid":"P298","v":"NLD"}]}}`

**Comment by tfrancart** [comment]
Thanks.

1. How does it explain the result with limit = 3 ?
2. In OpenRefine I can't specify that I both want to send the content of the column in the `query` parameter _and_ as an additionnal property, as only "other columns" are proposed for additionnal properties. Hmmm, should I duplicate the column to achieve this ?

**Comment by wetneb** [comment]
1. Results with mismatching types can be included in the reconciliation results, their scores are divided by 2 to penalize them.
2. Yes.

**Comment by tfrancart** [comment]
I think the behavior with the limit parameter is completely misleading. If we get 3 results with "limit=3", or some results when limit is not used, I don't see any reason (from a user point of view - I understand the technical explanations) why we don't get a result when limit=1 or 2.

Beside, I think the use-case of matching the query against an identifier property (and not against a label, or in addition to the label) should be considered (maybe within the W3C CG).

**Comment by wetneb** [comment]
> I think the behavior with the limit parameter is completely misleading. If we get 3 results with "limit=3", or some results when limit is not used, I don't see any reason (from a user point of view - I understand the technical explanations) why we don't get a result when limit=1 or 2.

I agree! This could be solved by not passing the limit to the search APIs. Would you be interested in doing a pull request for that?

> Beside, I think the use-case of matching the query against an identifier property (and not against a label, or in addition to the label) should be considered (maybe within the W3C CG).

Absolutely! You are more than welcome to join the CG and propose that - it is definitely something I would support.
