### ISSUE TITLE
Remove flyout services

### ISSUE THREAD

**Issue by wetneb** [wetneb/openrefine-wikibase#77]
Now that the suggest services return descriptions, we should remove the flyout service which is redundant.

Note that the flyout service and the suggest service might not return the same descriptions all the time at the moment (the flyout might use autodesc, which is more expensive to generate, and the suggest services only return descriptions stored in Wikidata itself).

**Comment by thadguidry** [comment]
Ah!  That's why we were seeing the differences!

**Comment by tfmorris** [comment]
Descriptions are often missing for many (or all) languages and, even when present, don't match the richness of the context provided by a preview pane which can include entity types, key dates, images, etc. If they are the same now, it sounds like the preview pane needs to be made richer, not removed.

**Comment by wetneb** [comment]
I think you are mixing up two different things: flyouts and previews. The preview pane is meant to give a rich view of the entity (as you describe), and appears when you hover reconciliation candidates or matched cells. I agree this preview service must be kept and improved.

The flyout service is different: it associates a short text snippet to each item in a suggest service. See https://github.com/OpenRefine/OpenRefine/issues/2334#issuecomment-591451270 for a screenshot, and see @VladimirAlexiev's comment below, which expresses pretty well my sentiment about this UI.
