### ISSUE TITLE
Using the service from a C# API

### ISSUE THREAD

**Issue by ZakiNata** [wetneb/openrefine-wikibase#78]
Hi,

when trying to get data from https://tools.wmflabs.org/openrefine-wikidata/en/api?queries=...
using POSTMAN I get the results without a problem
when trying to activate from inside a C# code I get the 'Forbidden' response, do you have any idea what I am missing here ?

Thanks a lot

**Comment by wetneb** [comment]
Hi!
It's hard to tell without looking at your code. Could you dump the POST and GET parameters you are sending in your C# code?

**Comment by ZakiNata** [comment]
Hi,

I was using a GET code that succeeded with other services like ORCID
afterwards I adjusted and used the code of rest sharp instead
it works when trying to send up to 7 queries, but when trying to activate it using open refine and open refine sends 10 queries batch, I get HTTP code 502 - bad gateway 

the new code used :
string wiki = "https://tools.wmflabs.org/openrefine-wikidata/en/api?" + queries;
var client = new RestSharp.RestClient(wiki);
client.Timeout = -1;
var request = new RestRequest(Method.GET);
IRestResponse response = client.Execute(request);

the same when trying to send the queries batch from a browser 

the previous GET code used :
private static async System.Threading.Tasks.Task<string> PerformGetAPICallAsync(string URL, string urlParameters)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(URL);

            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));

            HttpResponseMessage response = client.GetAsync(urlParameters).Result;  
            if (response.IsSuccessStatusCode)
            {
                var responseString = await response.Content.ReadAsStringAsync();
                return responseString.ToString();
            }
            else
            {
                Console.WriteLine("{0} ({1})", (int)response.StatusCode, response.ReasonPhrase);
            }
            client.Dispose();

            return null;
        }

**Comment by wetneb** [comment]
HTTP code 502 means that the service failed to reply, probably because it is overloaded.

**Comment by ZakiNata** [comment]
Yes I know, but the weird thing that wikidata replies to the same amount when called from open-refine, but doesn't when called from a browser or code
I'll try to divide the batch in my code :)

**Comment by wetneb** [comment]
HTTP 502 errors were an artifact of the toolforge deployment - the issue should hopefully be fixed by switching to the new endpoint: https://wikidata.reconci.link/en/api.
