### ISSUE TITLE
'DefaultTypes' not updated with third-party Wikibase instance

### ISSUE THREAD

**Issue by anchardo** [wetneb/openrefine-wikibase#81]
Hi Wetneb,
I'm testing your OpenRefine reconciliation service for my own Wikibase instance (thanks!). Globally it seems to work well, but I wonder if the DefaultTypes are hard-coded?
Despite having changes changed the QID of the "defaultTypes" (_all the relevant values must be configured in the config.py file_ ), this is still the former value
`defaultTypes": [{"name": "Q35120", "id": "Q35120"}]`
which is used/displayed in `http://localhost:8000/fr/api`.

**Comment by wetneb** [comment]
Thanks for trying it out, and thanks even more for your bug reports! :)

This is configured by `default_type_entity = "Q35120"` in `config.py`. That being said that only updates the id, not the label, and that is a bug! Let me fix that.
