### ISSUE TITLE
Can't add standard reconciliation service

### ISSUE THREAD

**Issue by pyrog** [wetneb/openrefine-wikibase#84]
On **Safari** Version 13.0.4 (14608.4.9.1.4), the box to add a reconciliation service don't open.
Work fine on **Chrome** and **Firefox**.

Console:
```
SyntaxError: Unexpected token '}'
(fonction anonyme) — project:74
project-bundle.js:10335

```
<img width="630" alt="Can't add a reconciliation service on Safari" src="https://user-images.githubusercontent.com/2158081/88482061-205c8b00-cf5f-11ea-99fd-3a26a0b00e79.png">

**Comment by wetneb** [comment]
Moving to the OpenRefine repository.
