### ISSUE TITLE
Service left panel bounce

### ISSUE THREAD

**Issue by pyrog** [wetneb/openrefine-wikibase#85]
When clicking on le "label" icon to hide/show the left panel, it "bounce" on **Chrome**.
Work nice on **Safari** and **Firefox**.

The javascript console don't display anything.

<img width="902" alt="Panel shown" src="https://user-images.githubusercontent.com/2158081/88482352-fd32db00-cf60-11ea-8e4b-d7e915a1688e.png">
<img width="900" alt="Panel hidden" src="https://user-images.githubusercontent.com/2158081/88482353-fdcb7180-cf60-11ea-834a-12c4eec5fc97.png">

**Comment by wetneb** [comment]
@pyrog this has been resolved in the OpenRefine master branch but has not been released yet: https://github.com/OpenRefine/OpenRefine/issues/2913

**Comment by pyrog** [comment]
nice, thank you 😃
