### ISSUE TITLE
Configuration for a custom Wikibase instance

### ISSUE THREAD

**Issue by johanricher** [wetneb/openrefine-wikibase#90]
I've deployed a reconciliation service and wrote a manifest for my Wikibase instance, to be able to use this new wonderful OpenRefine ability announced last month.

I've followed [the documentation](https://github.com/wetneb/openrefine-wikibase/blob/492f36d009d9d70ef003da9e6e70305369a63673/README.md#configuring-for-other-wikibase-instances-than-wikidata) to configure my reconciliation service. Then I added my custom Wikibase instance into OpenRefine (using [my manifest](https://gitlab.huma-num.fr/eurhisfirm/eurhisfirm-wikibase-openrefine/-/blob/master/eurhisfirm-wikibase-manifest.json)), but, when trying to reconcile a column, I can't select a different type than the one preselected for me. I get a "Sorry, something went wrong. Please try again later" error in the "Reconcile against type:" field.

![image](https://user-images.githubusercontent.com/10212787/93784822-b47c6300-fc2d-11ea-8a6b-865aea81498b.png)

There's a good chance that I misconfigured something in the `config.py` of my reconciliation service: https://gitlab.huma-num.fr/eurhisfirm/eurhisfirm-wikibase-openrefine/-/blob/master/config.py. It would definitely help me to compare with the configuration made for another Wikibase instance!

I also get the following CORS error in the Firefox console when the "Sorry, something went wrong..." message shows up, but I don't know if that's relevant:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8000/en/suggest/type?prefix=Q&spell=always&exact=false&scoring=schema&prefixed=true. (Reason: CORS request did not succeed).`

**Comment by wetneb** [comment]
The CORS error looks relevant.

Is the service really running on `http://localhost:8000`? If not, you need to change this line:
https://gitlab.huma-num.fr/eurhisfirm/eurhisfirm-wikibase-openrefine/-/blob/master/config.py#L62

**Comment by pyrog** [comment]
> I also get the following CORS error in the Firefox console when the "Sorry, something went wrong..." message shows up, but I don't know if that's relevant:
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8000/en/suggest/type?prefix=Q&spell=always&exact=false&scoring=schema&prefixed=true. (Reason: CORS request did not succeed).
> 
Your service must support suggest entity and CORS.

from flask_cors import CORS, cross_origin
@app.route('/<lang>/suggest/entity', methods=['GET'])
@cross_origin()
__
Yves

**Comment by johanricher** [comment]
> Is the service really running on http://localhost:8000?

Yes, on the server on which the reconciliation service runs, for `openrefine-wikibase_reconcile`, `docker ps` indicates `0.0.0.0:8000->8000/tcp`.

Note that wikibase-docker also runs on the same server, would that cause a conflict with the port?

> from flask_cors import CORS, cross_origin
> @app.route('/<lang>/suggest/entity', methods=['GET'])
> @cross_origin()

Should I add these lines in `config.py`? If no, where?

**Comment by wetneb** [comment]
> Should I add these lines in config.py? If not, where?

You should not need to add these lines anywhere (they are already in the source code of the service).

**Comment by johanricher** [comment]
Ok so this was indeed cause by the misconfiguration idenfied by @wetneb. I changed http://localhost:8000 to http://data.eurhisfirm.eu:8000 since it's the correct URL of the server on which the reconciliation service runs.

In OR, the UI error ("Sorry, something went wrong..." ) is still here but the console error changed: it's now trying to access the reconciliation service with `GET http://data.eurhisfirm.eu/en/suggest/type?prefix=Q1&spell=always&exact=false&scoring=schema&prefixed=true`

Except http://data.eurhisfirm.eu/en/suggest/ doesn't work because the correct URL is http://data.eurhisfirm.eu:8000/en/suggest/entity. I don't know why it's ignoring the port since it's in the config file.

**Comment by wetneb** [comment]
I don't have any problem with your service on my side (with OR 3.4):
![image](https://user-images.githubusercontent.com/309908/93805845-8c4e2d80-fc48-11ea-95f8-741ba734e24e.png)

It is correctly calling http://data.eurhisfirm.eu:8000/en/suggest/type?prefix=p&spell=always&exact=false&scoring=schema&prefixed=true

Which version of OpenRefine are you using?

**Comment by johanricher** [comment]
I'm running OR from a cloned repo (version 3.5-beta [076d302]). I'll try the 3.4 release.

**Comment by johanricher** [comment]
So, with 3.4 if I keep the reconciliation service I added in 3.5 using the "new workflow" which is based on the manifest, it's still using the incorrect URL (i.e. without the 8000 port).

But if I delete that and add the reconciliation service with the "Add Standard Service" workflow and input the correct URL (http://data.eurhisfirm.eu:8000/en/api), it's working.

**Comment by wetneb** [comment]
I am glad it works for you now! But that behaviour with the manifest sounds like a bug. Could you perhaps open an issue on https://github.com/OpenRefine/OpenRefine (basically expanding on your last message)?

**Comment by johanricher** [comment]
Will do! Thanks again

**Comment by johanricher** [comment]
(I tried on a different computer with a clean OR 3.5-beta [3fe2281] and can't reproduce the issue.)
