### ISSUE TITLE
Unable to get "Auto-match candidates with high confidence" working when reconciling to custom Wikibase

### ISSUE THREAD

**Issue by wetneb** [wetneb/openrefine-wikibase#92]
_Originally posted by @lozanaross at https://github.com/OpenRefine/OpenRefine/issues/3271_

This used to be possible and over the last week or so, it seems to be a problem, I can't get any "Auto-match candidates with high confidence" for text data. I can't identify that I'm doing anything else differently than usual, so not sure what's the issue other than a bug?

### To Reproduce
1. First, choose to reconcile text data (i.e. NOT ID numbers) against a custom Wikibase endpoint
2. Then, pick the right type to reconcile against & tick "Auto-match candidates with high confidence" 
3. Finally, see that none of the data is matched to anything & you have to do it all manually.

### Current Results
No columns with text data get matched to their high probability candidates. It has to be all done manually.

### Expected Behavior
Get auto-match suggestions, as usual.

### Screenshots
![Screenshot 2020-10-16 at 18 20 35](https://user-images.githubusercontent.com/25489750/96283576-18076f80-0fe5-11eb-8047-a6fdc27efcc3.png)
![Screenshot 2020-10-15 at 23 33 53](https://user-images.githubusercontent.com/25489750/96283593-1dfd5080-0fe5-11eb-854f-3f800521f6b3.png)

### Versions
- Operating System: MacOS Catalina 10.15.6
- Browser Version: Google Chrome Version 84.0.4147.135 (Official Build) (64-bit)
- JRE or JDK Version: JRE 1.8.0_261
- OpenRefine: OpenRefine master branch as of 14.10.2020

### Datasets
I have tried to reconcile against two available endpoints and get same issue with both:
https://reconciliation.artbase.rhizome.org/
http://rhizome-artbase.reconci.link/

**Comment by wetneb** [comment]
This might be caused by a change in the data stored by the Wikibase instance, but seems to be a genuine bug in the reconciliation service.

Without type restriction, it works: https://rhizome-artbase.reconci.link/en/api?queries=%7B%22q0%22%3A%7B%22query%22%3A%22Broken+Gradients%22%7D%7D

With type restriction: https://rhizome-artbase.reconci.link/en/api?queries=%7B%22q0%22%3A%7B%22query%22%3A%22Broken+Gradients%22%2C%22type%22%3A%22Q5%22%7D%7D

We currently obtain 

```
{
    "arguments": {
        "lang": "en",
        "queries": "{\"q0\":{\"query\":\"Broken Gradients\",\"type\":\"Q5\"}}"
    },
    "details": "args must not contain None",
    "message": "invalid query",
    "status": "error"
}
```

**Comment by lozanaross** [comment]
Yes, I'm also able to reconcile against QIDs directly. So I guess the type restriction is the problem. I do think this wasn't the case a few weeks ago when I first started using the service but it's possible I'm misremembering.

**Comment by wetneb** [comment]
This seems to be due to the fact that your query service returns items with URIs such as `http://wikibase.svc/entity/Q5` whereas they should be `http://artbase.rhizome.org/entity/Q5`.

https://tinyurl.com/y54a9d5q

**Comment by lozanaross** [comment]
OK, interesting – is this because OR runs the reconciliation service via the Sparql endpoint? So essentially we need to reconfigure our query service? We normally have to specify our custom prefixes and then we get correct results: https://tinyurl.com/y3xz4pnv

Just checking if this is also possibly the reason why I can't reconcile directly against whole URL identifiers, and only Q numbers alone work.

**Comment by wetneb** [comment]
You should adapt the configuration of the OR service to use the appropriate prefixes, then. There are probably some `wd:` or `wdt:` prefixes left in your `config.py`.

> Just checking if this is also possibly the reason why I can't reconcile directly against whole URL identifiers, and only Q numbers alone work.

This is because of the discrepancy between the `identifierSpace` declared in your `config.py` and the RDF URIs returned by your query service (one uses HTTPS, the other HTTP).

**Comment by lozanaross** [comment]
OK, got it, thanks! Will resolve with Rhizome team then, but it seems like this might be helpful to be mentioned somewhere in the documentation around the reconciliation service – that custom prefixes need to specified, and the discrepancy between https / http needs to be flagged (the latter is a common problem I've see in other wikibase instances).

**Comment by dlindem** [comment]
> 
> 
> _Originally posted by @lozanaross at [OpenRefine/OpenRefine#3271](https://github.com/OpenRefine/OpenRefine/issues/3271)_
> 
> This used to be possible and over the last week or so, it seems to be a problem, I can't get any "Auto-match candidates with high confidence" for text data. I can't identify that I'm doing anything else differently than usual, so not sure what's the issue other than a bug?
> ### To Reproduce
> 
> Steps to reproduce the behavior:
> 
>     1. First, choose to reconcile text data (i.e. NOT ID numbers) against a custom Wikibase endpoint
> 
>     2. Then, pick the right type to reconcile against & tick "Auto-match candidates with high confidence"
> 
>     3. Finally, see that none of the data is matched to anything & you have to do it all manually.
> 
Hi, I am experiencing the same problem. Reconciliation auto-match without type restriction works, but unfortunately is not an option; I need type restriction.

I am trying to reconcile against http://data.lexbib.org/entity/Q5 (human).

I have tried to change "identifier_space" from http to https, but that makes no difference. My config.py is [here](https://github.com/dlindem/openrefine-wikibase/blob/e5f54db5517ace4f6a6cd679864bf7daa38943e6/config.py#L42).

**Comment by wetneb** [comment]
Looking at your query service, it seems that the RDF prefixes you use need to be defined in each query:
```
PREFIX lwb: <http://data.lexbib.org/entity/>
PREFIX ldp: <http://data.lexbib.org/prop/direct/>
PREFIX lp: <http://data.lexbib.org/prop/>
PREFIX lps: <http://data.lexbib.org/prop/statement/>
PREFIX lpq: <http://data.lexbib.org/prop/qualifier/>
```
Have you tried including those prefixes in the SPARQL query `sparql_query_to_fetch_subclasses` defined in your `config.py`?

**Comment by dlindem** [comment]
Thanks for your quick reply, @wetneb, but adding the prefixes to that variable doesn't fix the problem; now restriction to Q5 class does not work at all (suggestions from all classes are shown).

And another question, if I may bother you with that:
In the screenshot example, a correct Qid is shown, and label and description in the "search for match" suggestions are also correct, but the preview shows data from wikidata, not from my wikibase. I can't see any wd: or wdt: left in my config.py; can I adapt that somehow?

![Bildschirmfoto von 2021-03-23 12-56-15](https://user-images.githubusercontent.com/34068491/112143705-8bd32700-8bd8-11eb-9fb4-8a74e6251457.png)

**Comment by wetneb** [comment]
You should disable the autosuggest service here: https://github.com/dlindem/openrefine-wikibase/blob/e5f54db5517ace4f6a6cd679864bf7daa38943e6/config.py#L110

**Comment by dlindem** [comment]
Yes, nice. Now I don't get previews from Wikidata, thanks.
The other problem (won't get auto-matching of candidates with high confidence when restricting recon to a class) persists.
