### ISSUE TITLE
Make syntax to fetch terms more discoverable

### ISSUE THREAD

**Issue by wetneb** [wetneb/openrefine-wikibase#96]
Originally posted by @tfmorris here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/openrefine/xZ3CQv2BOGI/WsJmRxkqAQAJ

> On Fri, Oct 30, 2020 at 11:41 AM @thadguidry wrote
> > 
> > 
> >     The Wikidata Reconcile endpoint already supports Language selection.
> >     https://wikidata.reconci.link/
> > 
> >     Special properties
> > 
> >     Labels, aliases and descriptions can be accessed as follows (L for label , D for description, A for aliases, S for sitelink):
> > 
> >         Len for Label in English
> >         Dfi for Description in Finnish
> >         Apt for Alias in Portuguese
> >         Sdewiki for Sitelink in German Wikipedia page titles
> > 
> 
> I should have remembered that since I just reviewed the documentation. These should be more discoverable -- perhaps included in autocomplete with a term like "label" instead of "L".

**Comment by tfmorris** [comment]
Having fake pseudo properties that could be served by the property autocomplete seems like a possible solution (although I have no idea why they're not accessible directly from Wikidata), but supporting language selection seems tricky. Making the lookup more exotic, like "label@en" or "nom@fr", doesn't seem very satisfying, but I don't know what other possibilities there are.

**Comment by wetneb** [comment]
Those are now documented on the main page of the service, and that's the best we can do given the absence of in-client documentation (the API does not let us expose that).
