### ISSUE TITLE
enable inverse path as additional prop

### ISSUE THREAD

**Issue by VladimirAlexiev** [wetneb/openrefine-wikibase#97]
Use case:
- I have a table with Fortune 500 companies and their CEOs.
- I first match the company, then match the CEO
- When matching the CEO, I'd like to use P1037 director / manager. However, that prop goes in the other direction (company-CEO).

So I'd like to specify `^P1037` as additional prop of CEO, and select the reconciled Company as value.

**Comment by VladimirAlexiev** [comment]
There's also P1875 represented by, so a combination of inverse and disjunction will also be useful: `^P1037|^P1875` or `^(P1037|P1875)`

**Comment by thadguidry** [comment]
@VladimirAlexiev Why not use [P169 chief executive officer](https://www.wikidata.org/wiki/Property:P169) ?

**Comment by wetneb** [comment]
We would need to design a way to fetch these property values, probably via SPARQL, and assess the performance implications.

**Comment by VladimirAlexiev** [comment]
@thadguidry that would mean we need `^(P1037|P1875|P169)`

**Comment by wetneb** [comment]
No way to implement this in an efficient way given the current architecture, sadly.
